### ISSUE TITLE
Use

### ISSUE THREAD

**Issue by MoMMde** [Jilence/mojang-api#1]
A
Fucking

DEPENDENCIE FOR JSON!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# U STUPID?!?!??

**Comment by MoMMde** [comment]
Du benutzt nichtmal MAVEN!?!@?!?!?!?!

**Comment by MoMMde** [comment]
ODER GRADLE

**Comment by MoMMde** [comment]
DAS IST DAS SCHLIMMSTE WAS ICH JEMALS GESEHEN HABE

**Comment by MoMMde** [comment]
![image](https://user-images.githubusercontent.com/80107781/125209130-0bbff280-e297-11eb-9a9c-935065f3715e.png)

**Comment by Jilence** [comment]
ja ist eehr gjt
